// O THIS É UMA PLAVRA RESERVADA DO JS PARA NOS REFERIRMOS A NOSSA ESTRUTURA ATUAL. ELA É MUITO UTILIZADA DENTRO DE CLASSES E OBJETOS PRINCIPALMENTE EM OUTRAS LINGUAGENS.

// NO JAVASRCRIPT, O THIS PODE SER USADO EM FUNÇÕES E TENDE A REFERIR A AQUELA MESMA ESTRUTURA EM QUE ELE ESTÁ INSERIDO

// MAS NEM SEMPRE ISSO PODE ACONTECER, PORQUE NO JAVASCRIPT, QUANDO USAMOS FUNCTION DO JEITO TRADICIONAL, O THIS PODE VARIAR DE ACORDO COM QUEM CHAMOU A FUNÇÃO

// PORÉM, UMA DAS VANTAGENS DE SE USAR ARROW FUNCTION É QUE O THIS NÃO VARIA, ELE SEMPRE APONTARÁ PARA A FUNÇÃO EM QUE ELE ESTÁ INSERIDO

// O THIS SERÁ DEFINIDO A PARTIR DO MOMENTO EM QUE VOCÊ DEFINIR O TIPO DE FUNÇÃO. E ENTÃO O THIS SERÁ DEFINIDO A PARTIR DESSE CONTEXTO DO QUAL A FUNÇÃO FOI DEFINIDA